Added new feature for read function (issue #9)
varun-iyer/sdi_pipeline pull request #12
Opened 2021-04-11 00:28 UTC by EdgarMao

file chooser pops up when directory is not designated

2021-04-11 01:18 UTC, EdgarMao commented
The first commit had significant problems, the second commit works well.

2021-04-12 18:09 UTC, varun-iyer commented
@EdgarMao , what behavior does this have if the user doesn't have an x session running (e.g. over an ssh session)

2021-04-12 23:00 UTC, EdgarMao commented
> @EdgarMao , what behavior does this have if the user doesn't have an x session running (e.g. over an ssh session)

I have only ran this on starmaker and my personal computer locally so far, and it works fine in both cases. Since the tkinter library is fairly common on most windows and unix systems, I would imagine it working fine most of the time (I haven't really checked).

2021-04-13 01:56 UTC, varun-iyer commented
This is good! Please add a sensible error message if a tkinter window cannot be opened due to ssh/other reason.

2021-04-20 03:49 UTC, EdgarMao commented
Hey Varun, in the lastest commit I added the feature where if any error occurs when the file dialog is called, the program will output the following message: "Visual file dialog does not exist, please specify path to directory to save fitsfiles."

2021-04-21 01:54 UTC, varun-iyer requested changes

2021-04-21 01:54 UTC, varun-iyer commented on commands/fitsio.py
> +        except:
This looks good Edgar! However, `except` without specifying a kind of error to except is a bad practice. For example, if the directory given to glob does not exist, glob might throw a FileNotFoundError, which would be caught by `except`, resulting in the very strange error message of having a visual file dialog not exist.

A good fix which does catch all tkinter errors might be to separate out the `tkinter.filedialog.askdirectory()` into its own try-catch, leaving the glob part separate.

2021-04-21 01:54 UTC, varun-iyer commented on commands/fitsio.py
> +            print("Visual file dialog does not exist, please specify path to directory to save fitsfiles.")
Use `click.echo` with `err=True` over `print` when possible!

2021-04-21 01:54 UTC, varun-iyer commented on commands/fitsio.py
> +            print("Visual file dialog does not exist, please specify path to directory to save fitsfiles.")
Also, this error message could be a little more specific: e.g., specify path to directory to _read_ fitsfiles with `-d` or something.

2021-04-21 04:34 UTC, EdgarMao commented
Both issues have been resolved, please check the latest commit. Thanks!

2021-04-23 06:24 UTC, varun-iyer commented
swallowed + merge in pr #17

2021-04-23 06:24 UTC, closed without merging